Nats v2 migrate
cloudfoundry/nats-release pull request #45
Opened 2022-06-22 22:39 UTC by reneighbor

2022-06-22 22:55 UTC, jrussett commented on example-manifests/nats.yml
> +  - name: royalorange-pas-subnet
We should probably change it back to `default`

2022-06-23 19:58 UTC, mariash requested changes

2022-06-23 19:58 UTC, mariash commented on jobs/nats-tls/monit
> +  depends on nats-tls
Thinking we don't need to make it dependent on natst-tls, if nats gets restarted we don't need to restart migrate server. Communication between migrate servers happens in post-start so everything will be started.

2022-06-23 19:58 UTC, mariash commented on jobs/nats/monit
> +  depends on nats
same here, probably don't need `depend on nats`

2022-06-23 19:58 UTC, mariash commented on jobs/nats-tls/templates/migrator-config.json.erb
> +    instance_id = ""
why do we need this variable? we can probably just use `spec.id` on line 20

2022-06-23 19:58 UTC, mariash commented on jobs/nats-tls/monit
> +check process migrate-server
I wonder if anyone collocates `nats` and `nat-tls` on the same machine? In that case the name `migrate-server` for both will collide.

2022-06-23 19:58 UTC, mariash commented on jobs/nats/templates/migrator-config.json.erb
> +    instance_id = ""
same here, probably don't need this variable and just use `spec.id` below

2022-06-23 19:58 UTC, mariash commented on jobs/nats/templates/post-start.erb
> +/var/vcap/packages/nats-v2-migrate/bin/migrate --config-file /var/vcap/jobs/nats/config/migrator-config.jso
this is a typo, missing `n`. We should test migration for `nats`

2022-06-23 19:58 UTC, mariash commented on spec/nats/nats_config_spec.rb
> -
These tests should still be here. If `tls_cluster_port` is provided we want to include routes to them.

2022-06-23 19:58 UTC, mariash commented on src/code.cloudfoundry.org/nats-v2-migrate/cmd/migrate/main.go
> +	if bootstrapMigrateServer == "" {
I think there might be a case when the current server will be bootstrap server.

Imagine if there is high max_in_flight and a bunch of nats instances will be updated at the same time. There is a chance still that bootstrap instance with index 0 might run post-start as latest. We should check if `conf.Bootstrap` is set when setting `bootstrapMigrateServer`

2022-06-23 19:58 UTC, mariash commented on src/code.cloudfoundry.org/nats-v2-migrate/cmd/migrate/main.go
> +				if err != nil {
we can either remove this or put it in `else`

2022-06-23 19:58 UTC, mariash commented on src/code.cloudfoundry.org/nats-v2-migrate/cmd/migrate/main.go
> +func makeRequest(url string, ch chan<- string) {
I don't see that this function is used

2022-06-23 19:58 UTC, mariash commented on src/code.cloudfoundry.org/nats-v2-migrate/integration/server_test.go
> +	fmt.Printf(certDepoDir + "\n")
probably can clean up fmt.printf debugging info in this method

2022-06-23 19:58 UTC, mariash commented on src/code.cloudfoundry.org/nats-v2-migrate/server/main.go
> +	gCfg = cfg
pass bootstrap info to server on line 34 instead of using global config

2022-06-23 19:58 UTC, mariash commented on src/code.cloudfoundry.org/nats-v2-migrate/server/main.go
> +	if s.migrateEndpointHit == true {
we should protect this variable with lock to be thread safe

2022-06-23 19:58 UTC, mariash commented on src/code.cloudfoundry.org/nats-v2-migrate/server/main.go
> +	w.WriteHeader(http.StatusOK)
We should move this after restartNATS (:103) If we remove `depends on nats` in monit file restarting nats should not trigger migration server restart

2022-06-23 19:58 UTC, mariash commented on src/code.cloudfoundry.org/nats-v2-migrate/server/main.go
> +		cmd := exec.Command(gCfg.MonitPath, "restart", "nats-tls")
The same server runs for non tls `nats`? We can make the nats monit name configurable and pass in to server.

2022-06-23 19:58 UTC, mariash commented on src/code.cloudfoundry.org/nats-v2-migrate/server/main.go
> +		cmd := exec.Command(gCfg.MonitPath, "stop", "nats-tls")
Same here. Not going to work for non-tls nats

2022-06-30 21:58 UTC, merged