Nats 5.0 fail v1
cloudfoundry/nats-release pull request #57
Opened 2023-07-14 21:42 UTC by reneighbor

* We added a migration wrapper for nats in https://github.com/cloudfoundry/nats-release/releases/tag/v46
* The post-start script should check if the local nats instance is on v2; fail deployment (rolling back to v1) if not. The operator can take steps accordingly.
* Tested with 100% max-in-flight to make sure that we don't have a partial migration (and nats split-brain)
* This will be accompanies by a TAS PR to enable `fail_deployment_if_v1` in 5.0+

Reviewers: @ameowlia

2023-07-17 14:26 UTC, ameowlia requested changes
Can you remove all references to TAS from your comments? Yes this will affect TAS users, but it will also affect cf-d users when we turn this on in cf-d (which we should).

2023-07-17 14:26 UTC, ameowlia commented on src/code.cloudfoundry.org/nats-v2-migrate/cmd/fail-deployment-on-v1/main.go
> +	Bootstrap bool `json:"bootstrap"`
I see a bootstrap property here, but I don't see it used anywhere.

I am worried that this code will run on every nats VM in a deployment, and if they weren't on v2, then _all_ nats VMs would be taken offline. This is an issue. We only want to take 1 nats VM offline as a warning.

2023-07-19 14:08 UTC, ameowlia approved these changes

2023-07-24 17:56 UTC, merged

2023-07-25 07:15 UTC, plowin commented
Hi @reneighbor, does this only affect deployments that are still on nats-server < 2.x? I.e. we are fine if our envs show:
```
/var/vcap/data/packages/nats-server/cb6e9f9f539539dce7627019ba7e25be73be1810/bin# ./nats-server --version
nats-server: v2.9.17
```